spring:
  profiles:
    active: dev
  profiles-active: keycloak

server:
  port: 3001

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

baseUrl: http://localhost:3001/
